
server:
  port: 8091

spring:
  application:
    name: mos
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/test?currentSchema=mos}
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 50
        one-indexed-parameters: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: mos
  flyway:
    schemas: mos
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://auth.mos-hack.ru/realms/hackathon

app:
  upload:
    dir: ./uploads                    # можно переопределить: /var/www/mosstroy/uploads
    base-url: http://localhost:8091/files   # в продакшене будет https://cdn.example.com
